queries = [
            'engineering firms',
            'machining companies',
            'PCB population company',
            'PCB fabrication company',
            'PCB fabrication service',
            'industrial 3D printing company',
            'composite layup company',
            'CNC tooling foam company',
            'tooling foam company',
            'aircraft fabric company',
            'aircraft fabric supplier',
            'local tech companies',
            'rapid prototyping facilities',
            'additive manufacturing company',
            'automotive companies',
            'fabrication companies',
            'battery companies',
            'analysis software',
            'electronic hardware companies',
            'annodizing companies',
            'NAS bolt companies',
            'aluminum suppliers',
            'metal stock companies',
            'robotics companies',
            'automation companies',
            'mechanical engineering companies',
            'automotive engineering companies',
            'CNC machining companies',
            'local racetracks',
            'go kart facilities',
            'fabrication services',
            'automobile showcases',
            'automotive dealerships',
            'car dealerships',
            'sports car dealerships',
            'powder coating companies',
          ]
